### ISSUE TITLE
Generate initil charp client

### ISSUE THREAD

**Issue by hleb-albau** [regulaforensics/DocumentReader-web-csharp-client#1]
В целом клиент на charp больше всего похож на java клиент. Из-застатической типизации, добавить методы в какую-нибудь сгенерируемую модель становится немногосложнее.
https://github.com/regulaforensics/DocumentReader-web-java-client/blob/master/dev.md разработка под java, генератор сейчас стоит брать 5.0.0-beta.2 версии
В целом нужно двигаться примерно так:

- [x] Сгенерировать версию как есть
- [x] Добавить example, где просто проверить, что клиент парсит результат
- [x] Сделать, чтобывместо enum генерились простые типы(строки, инты)
- [x] Добавить доп  методы для классов Text, TextField, Images, ImageField( смотри тут https://github.com/regulaforensics/DocumentReader-web-java-client/tree/master/client/src/main/java/com/regula/documentreader/webclient/model и коммиты как это добавлялось в java)
- [x] Сделать модель для неизвестного типа контейнера (https://github.com/regulaforensics/DocumentReader-web-java-client/blob/master/client/src/main/java/com/regula/documentreader/webclient/RawResultItem.java)
- [x] Проверить, что работа с картинками происходит и в байтах(есть методы которые не только base64 принимают, но и bytes)
- [x] Привести пример, чтобы он выл точь-в-точь как в java(все названия доп методов и т.д. должны совпадать)
- [x] Настроить проверку выполнения примера на каждый коммит в githubactions
- [x] Настроить сборку и заливку либы по тэгу в githubactions
- [x] Общий ридми (такой же как в java)
- [x] Ридми запуска примера (такой же как в java)

**Comment by AlexSatsukevich** [comment]
Реализовал RawResultItem путем реализации интерфейса IDictionary<string, object>. Теперь если тип контейнера не определен получаем словарь. Пример см в Regula.DocumentReader.WebClientTest.ResponseTest

**Comment by hleb-albau** [comment]
done
