### ISSUE TITLE
Asp.net Core: Getting the content of PercentValue 

### ISSUE THREAD

**Issue by Lug16** [regulaforensics/DocumentReader-web-csharp-client#113]
Hi all...

I've been struggling for hours with the way to get from the response object, the value of the field PercentValue when comparing docs and selfies.
I'm using "Regula.DocumentReader.WebClient" Version="7.4.43" 
According to the json structure I got from the response it is located in:

response►ContainerList►List►10►ListVerifiedFields►pFieldMaps►0►Matrix►3

But using the library in C# does not show anything under AuthenticityCheckList or any other property

Can you please help me with this?

BR

**Comment by KirylKovaliov** [comment]
Thank you for reporting this issue and for providing detailed information. We appreciate your help in identifying the bug.

While we work on fixing this, could you please share more details about your use case? Specifically, we’d like to understand why you need to access the comparison percentage values. This information will help us better address your needs and potentially improve our solution.

**Comment by GubinAlexander** [comment]
Hello @Lug16 
We have just released new v7.4.44 version. In this version you show be able to get PercentValue by this path: `response.Authenticity().List[0].List[0].PercentValue`
Also please keep in mind every `PercentValue` field locates in AuthenticityCheckList container.
Please feel free to test this approach and let us know if you will have any issues.

**Comment by Lug16** [comment]
Hi @GubinAlexander 
Thank you for your response and also sorry for my extreme late reply.
I tested your approach, using "Regula.DocumentReader.WebClient" Version="7.7.306" 
But:
`response.Authenticity()
null`

So the entire line:
`response.Authenticity().List[0].List[0].PercentValue;`

Is giving null reference exception :(

Any advice will be very appreciated
